### ISSUE TITLE
Add an ORM framework

### ISSUE THREAD

**Issue by Hudson-obai** [SpaceyaTech/Team-Berlin-Springboot#10]
Add Spring Data JPA For automatic mapping of models into entities in the database

**Comment by sydneymainga** [comment]
I beleave this one too has been handled 

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

**Comment by sydneymainga** [comment]
Done
