### ISSUE TITLE
Define Application Models 

### ISSUE THREAD

**Issue by Hudson-obai** [SpaceyaTech/Team-Berlin-Springboot#2]
Based on the Entity Relational Diagrams, create the core models to be used within the application

**Comment by sydneymainga** [comment]
worked on this PR : https://github.com/SpaceyaTech/Team-Berlin-Springboot/pull/14

**Comment by sydneymainga** [comment]
done on this PR : https://github.com/SpaceyaTech/Team-Berlin-Springboot/pull/14
