### ISSUE TITLE
Set Up Database For The Application

### ISSUE THREAD

**Issue by Hudson-obai** [SpaceyaTech/Team-Berlin-Springboot#9]
Download database dependencies and define application properties for local development

**Comment by sydneymainga** [comment]
I already worked on this from the skeleton application i created.Kindly advise.

datasource:
    password: 'berlin'
    url: jdbc:postgresql://localhost:5432/berlinspringboot
    username: 'berlin'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
